# Generated by Django 6.0.7 on 2026-07-12 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('settings_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSRActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=50)),
                ('category', models.ForeignKey(limit_choices_to={'type': 'csr'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_admin.category')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_admin.department')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.FileField(blank=True, null=True, upload_to='proofs/csr/')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('points_earned', models.IntegerField(default=0)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='social.csractivity')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csr_participations', to='authentication.employee')),
            ],
            options={
                'unique_together': {('employee', 'activity')},
            },
        ),
    ]
