# Generated by Django 6.0.7 on 2026-07-12 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('settings_admin', '0001_initial'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('completion_deadline', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='trainings', to='authentication.employee')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='settings_admin.department')),
            ],
        ),
    ]
