# Generated by Django 6.0.7 on 2026-07-12 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmental_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('social_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('governance_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('period', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='settings_admin.department')),
            ],
            options={
                'unique_together': {('department', 'period')},
            },
        ),
    ]
