# Generated by Django 6.0.7 on 2026-07-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('esg_manager', 'ESG / Sustainability Manager'), ('dept_head', 'Department Head / Manager'), ('employee', 'Employee'), ('compliance_officer', 'Compliance Officer / Auditor'), ('executive', 'Executive / Viewer')], default='employee', max_length=50)),
                ('xp', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
    ]
