import os
from django.conf import settings
from reportlab.pdfgen import canvas
from openpyxl import Workbook

def generate_pdf_report(report_request):
    filename = f"report_{report_request.id}.pdf"
    file_path = os.path.join(settings.MEDIA_ROOT, 'reports', filename)
    os.makedirs(os.path.dirname(file_path), exist_ok=True)

    c = canvas.Canvas(file_path)
    c.drawString(100, 800, f"EcoSphere Report ID: {report_request.id}")
    c.drawString(100, 780, f"Generated By: {report_request.generated_by.user.username if report_request.generated_by else 'System'}")
    c.drawString(100, 760, f"Date: {report_request.generated_at.strftime('%Y-%m-%d %H:%M:%S')}")
    
    # Placeholder for actual data fetching based on filters_snapshot
    c.drawString(100, 720, "This is a placeholder PDF report.")
    c.drawString(100, 700, f"Filters applied: {report_request.filters_snapshot}")
    
    c.save()
    
    report_request.file.name = f"reports/{filename}"
    report_request.save(update_fields=['file'])

def generate_excel_report(report_request):
    filename = f"report_{report_request.id}.xlsx"
    file_path = os.path.join(settings.MEDIA_ROOT, 'reports', filename)
    os.makedirs(os.path.dirname(file_path), exist_ok=True)

    wb = Workbook()
    ws = wb.active
    ws.title = "Report"
    
    ws.append(["EcoSphere Report ID", report_request.id])
    ws.append(["Generated By", report_request.generated_by.user.username if report_request.generated_by else 'System'])
    ws.append(["Date", report_request.generated_at.strftime('%Y-%m-%d %H:%M:%S')])
    ws.append(["Filters applied", str(report_request.filters_snapshot)])
    
    wb.save(file_path)
    
    report_request.file.name = f"reports/{filename}"
    report_request.save(update_fields=['file'])
