# Generated by Django 6.0.7 on 2026-07-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='report_type',
            field=models.CharField(default='custom', max_length=100),
        ),
        migrations.AlterField(
            model_name='reportrequest',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10),
        ),
    ]
