# Generated by Django 6.0.7 on 2026-07-12 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('csr', 'CSR Activity'), ('challenge', 'Challenge')], max_length=50)),
                ('status', models.CharField(default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ESGConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmental_weight', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('social_weight', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('governance_weight', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_emission_calculation', models.BooleanField(default=True)),
                ('evidence_requirement', models.BooleanField(default=True)),
                ('badge_auto_award', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('employee_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='authentication.employee')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_departments', to='settings_admin.department')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=100)),
                ('channel', models.CharField(default='both', max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='authentication.employee')),
            ],
            options={
                'unique_together': {('employee', 'notification_type')},
            },
        ),
    ]
